project:
  id: workload-149313

datastore:
  connectTimeout: 10
  readTimeout: 30

endpoints:
  health:
    path: /_ah/health

logbook:
    exclude:
        - /_ah/health
        - /admin/**
    filter.enabled: true
    format.style: json
    obfuscate:
        headers:
            - Authorization
            - X-Secret
        parameters:
            - access_token
            - password
    write:
        category: http.wire-log
        level: INFO

---

spring:
  profiles: development

project:
  authKeyFile: workload-service-auth.json

datastore:
  host: localhost:8045